# Generated by Django 2.2.6 on 2019-10-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rev',
            name='genre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
