# Generated by Django 2.2.6 on 2019-10-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_rev_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='rev',
            name='age',
            field=models.CharField(choices=[('1', 'Toddlers'), ('2', 'Kids'), ('3', 'Young Adult'), ('4', 'College'), ('5', 'Adults')], max_length=50, null=True),
        ),
    ]
