# Generated by Django 2.2.6 on 2019-10-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_rev_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rev',
            name='genre',
            field=models.CharField(choices=[('1', 'Sci-Fi'), ('2', 'Mystery'), ('3', 'Children'), ('4', 'Horror'), ('5', 'Political Thriller'), ('6', 'Self-Help'), ('7', 'Biography'), ('8', 'Textbook'), ('9', 'Picture Book'), ('10', 'Travel')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rev',
            name='review',
            field=models.TextField(max_length=2000),
        ),
    ]
