# Generated by Django 2.2.6 on 2019-10-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20191010_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rev',
            name='age',
            field=models.CharField(choices=[('Toddler', 'Toddlers'), ('Kids', 'Kids'), ('Young Adult', 'Young Adult'), ('College', 'College'), ('Adults', 'Adults')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rev',
            name='genre',
            field=models.CharField(choices=[('Sci-FI', 'Sci-Fi'), ('Mystery', 'Mystery'), ('Children', 'Children'), ('Horror', 'Horror'), ('Political Thriller', 'Political Thriller'), ('Self-Help', 'Self-Help'), ('Biography', 'Biography'), ('Textbook', 'Textbook'), ('Picture Book', 'Picture Book'), ('Travel', 'Travel')], max_length=50, null=True),
        ),
    ]
